// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MqttMsg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "MqttMsg.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - MqttMsgRoot

@implementation MqttMsgRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - MqttMsgRoot_FileDescriptor

static GPBFileDescriptor *MqttMsgRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - MqttMsg

@implementation MqttMsg

@dynamic version;
@dynamic codec;
@dynamic security;
@dynamic type;
@dynamic data_p;

typedef struct MqttMsg__storage_ {
  uint32_t _has_storage_[1];
  NSString *version;
  NSString *codec;
  NSString *security;
  NSString *type;
  NSData *data_p;
} MqttMsg__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "version",
        .dataTypeSpecific.className = NULL,
        .number = MqttMsg_FieldNumber_Version,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(MqttMsg__storage_, version),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "codec",
        .dataTypeSpecific.className = NULL,
        .number = MqttMsg_FieldNumber_Codec,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(MqttMsg__storage_, codec),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "security",
        .dataTypeSpecific.className = NULL,
        .number = MqttMsg_FieldNumber_Security,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(MqttMsg__storage_, security),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "type",
        .dataTypeSpecific.className = NULL,
        .number = MqttMsg_FieldNumber_Type,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(MqttMsg__storage_, type),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "data_p",
        .dataTypeSpecific.className = NULL,
        .number = MqttMsg_FieldNumber_Data_p,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(MqttMsg__storage_, data_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MqttMsg class]
                                     rootClass:[MqttMsgRoot class]
                                          file:MqttMsgRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MqttMsg__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
